# Generated by Django 4.2.2 on 2023-06-09 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('sap_number', models.PositiveIntegerField()),
                (
                    'supplier',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='delivery.supplier',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('shipment_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('shipment_week', models.PositiveSmallIntegerField()),
                ('delivery_week', models.PositiveSmallIntegerField()),
                (
                    'material',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='delivery.material',
                    ),
                ),
                (
                    'supplier',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='delivery.supplier',
                    ),
                ),
            ],
        ),
    ]
