# Generated by Django 4.2.2 on 2023-06-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0002_alter_delivery_delivery_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delivery",
            options={"verbose_name": "Поставка", "verbose_name_plural": "Поставки"},
        ),
        migrations.AlterModelOptions(
            name="material",
            options={"verbose_name": "Материал", "verbose_name_plural": "Материалы"},
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={"verbose_name": "Поставщик", "verbose_name_plural": "Поставщики"},
        ),
        migrations.AddField(
            model_name="material",
            name="description",
            field=models.CharField(default=123, max_length=250),
            preserve_default=False,
        ),
    ]
